
dist: trusty
sudo: false

language: c

env:
  - ELECTRON_CACHE=$HOME/.cache/electron

matrix:
  include:
    - os: osx
      osx_image: xcode9.0
      language: node_js
      node_js: "10"

    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

addons:
  apt:
    packages:
      - icnsutils

before_install:
  - curl -o- --location https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - nvm install 10
  - yarn install --frozen-lockfile

script:
  - yarn ci

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

