name: Build
on: [push, pull_request]
env: 
  ELECTRON_CACHE: $HOME/.cache/electron

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    env: 
      CC: clang
      CXX: clang++ 
      npm_config_clang: 1
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install --frozen-lockfile
      - run: yarn ci

  build-mac:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install --frozen-lockfile
      - run: yarn ci
  
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install --frozen-lockfile
      - run: yarn ci
